# Generated by Django 5.0 on 2023-12-11 13:57

from django.db import migrations


def create_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User(name='John Lenon', email="jognlenon@email.com", description= "im a John Lenon").save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]