# Generated by Django 5.0 on 2023-12-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=240, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrationDate',
            field=models.DateField(auto_now_add=True, verbose_name='Registration Date'),
        ),
    ]
