adapters = {"iclass" : "CAAGCAGAAGACGGCATACGAGAT"
           }



primers = {
    "primer1": "ACGAGACTGATTCAAGCAGAAGACGGCATACGAGAT", #i1_fw_v7
    "primer2": "GCTGTACGGATTCAAGCAGAAGACGGCATACGAGAT", #i2_fw_v7
    "primer3": "ATCACCAGGTGTCAAGCAGAAGACGGCATACGAGAT", #i3_fw_v7
    "primer4" : "TGGTCAACGATACAAGCAGAAGACGGCATACGAGAT", #i4_fw_v7
    "primer5" : "ATCGCACAGTAACAAGCAGAAGACGGCATACGAGAT", #i5_fw_v7
    "primer6" : "GTCGTGTAGCCTCAAGCAGAAGACGGCATACGAGAT", #i6_fw_v7
    "primer7" : "AGCGGAGGTTAGCAAGCAGAAGACGGCATACGAGAT", #i7_fw_v7
    "primer8" : "ATCCTTTGGTTCCAAGCAGAAGACGGCATACGAGAT", #i8_fw_v7
    "primer9" : "TACAGCGCATACAATGATACGGCGACCACCGAGATC", #lu_pcr_i1_rv_v7 ...
    "primer10" : "ACCGGTATGTACAATGATACGGCGACCACCGAGATC",
    "primer11" : "AATTGTGTCGGAAATGATACGGCGACCACCGAGATC",
    "primer12" : "TGCATACACTGGAATGATACGGCGACCACCGAGATC",
    "primer13" : "AGTCGAACGAGGAATGATACGGCGACCACCGAGATC",
    "primer14" : "ACCAGTGACTCAAATGATACGGCGACCACCGAGATC",
    "primer15" : "GAATACCAAGTCAATGATACGGCGACCACCGAGATC",
    "primer16" : "GTAGATCGTGTAAATGATACGGCGACCACCGAGATC",
    "primer17" : "TAACGTGTGTGCAATGATACGGCGACCACCGAGATC",
    "primer18" : "CATTATGGCGTGAATGATACGGCGACCACCGAGATC",
    "primer19" : "CCAATACGCCTGAATGATACGGCGACCACCGAGATC",
    "primer20" : "GATCTGCGATCCAATGATACGGCGACCACCGAGATC",
    "primer21"   :'AATCAGTCTCGTATCTCGTATGCCGTCTTCTGCTTG', #комплиментарные и перевернутые 
    "primer22"  :'AATCCGTACAGCATCTCGTATGCCGTCTTCTGCTTG',
     "primer23" : 'ACACCTGGTGATATCTCGTATGCCGTCTTCTGCTTG',
     "primer24" : 'TATCGTTGACCAATCTCGTATGCCGTCTTCTGCTTG',
     "primer25" : 'TTACTGTGCGATATCTCGTATGCCGTCTTCTGCTTG',
     "primer26" : 'AGGCTACACGACATCTCGTATGCCGTCTTCTGCTTG',
     "primer27" : 'CTAACCTCCGCTATCTCGTATGCCGTCTTCTGCTTG',
     "primer28" : 'GAACCAAAGGATATCTCGTATGCCGTCTTCTGCTTG',
     "primer29" : 'GTATGCGCTGTAGATCTCGGTGGTCGCCGTATCATT',
     "primer30" : 'GTACATACCGGTGATCTCGGTGGTCGCCGTATCATT',
     "primer31" : 'TCCGACACAATTGATCTCGGTGGTCGCCGTATCATT',
     "primer32" : 'CCAGTGTATGCAGATCTCGGTGGTCGCCGTATCATT',
     "primer33" : 'CCTCGTTCGACTGATCTCGGTGGTCGCCGTATCATT',
     "primer34" : 'TGAGTCACTGGTGATCTCGGTGGTCGCCGTATCATT',
     "primer35" : 'GACTTGGTATTCGATCTCGGTGGTCGCCGTATCATT',
     "primer36" : 'TACACGATCTACGATCTCGGTGGTCGCCGTATCATT',
     "primer37" : 'GCACACACGTTAGATCTCGGTGGTCGCCGTATCATT',
     "primer38" : 'CACGCCATAATGGATCTCGGTGGTCGCCGTATCATT',
     "primer39" : 'CAGGCGTATTGGGATCTCGGTGGTCGCCGTATCATT',
     "primer40" : 'GGATCGCAGATCGATCTCGGTGGTCGCCGTATCATT',
    }
#словарь со всеми праймерами
names = []
for ip in range(40):
    names.append(list(primers)[ip]) #генерируем названия праймеров для более удобной работы 